import type { ReportHeadersData } from "../Types";

export const GAMES_REPORT_HEADERS: ReportHeadersData[] = [
  {
    title: "Game ID",
    align: "start",
    sortable: false,
    value: "game_id",
  },
  {
    title: "Game Title",
    align: "start",
    sortable: false,
    value: "game_name",
  },
  {
    title: "Operator",
    align: "start",
    sortable: false,
    value: "site_id",
  },
  {
    title: "Brands",
    align: "start",
    sortable: false,
    value: "total_brands",
  },
  {
    title: "Total wagered (€)",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    title: "Total payouts (€)",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    title: "Total Refounds (€)",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    title: "GGR (€)",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    title: "Bonus bets (€)",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    title: "Bonus wins (€)",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    title: "Bonus GGR (€)",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    title: "RTP%",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    title: "AVG Bets (€)",
    align: "start",
    sortable: false,
    value: "avg_bets",
  },
  {
    title: "Players",
    align: "start",
    sortable: false,
    value: "total_players",
  },
  {
    title: "Sessions Number",
    align: "start",
    sortable: false,
    value: "total_sessions",
  },
  {
    title: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
];

export const PLAYERS_REPORT_HEADERS: ReportHeadersData[] = [
  {
    title: "Player ID",
    align: "start",
    sortable: false,
    value: "player_id",
  },
  {
    title: "Brand Name",
    align: "start",
    sortable: false,
    value: "brand",
  },
  {
    title: "Total wagered (€)",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    title: "Total payouts (€)",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    title: "Total Refounds (€)",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    title: "GGR (€)",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    title: "Bonus bets (€)",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    title: "Bonus wins (€)",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    title: "Bonus GGR (€)",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    title: "RTP%",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    title: "AVG Bets (€)",
    align: "start",
    sortable: false,
    value: "avg_bets",
  },
  {
    title: "Sessions Number",
    align: "start",
    sortable: false,
    value: "total_sessions",
  },
  {
    title: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
];

export const SESSIONS_REPORT_HEADERS: ReportHeadersData[] = [
  {
    title: "Session ID",
    align: "start",
    sortable: false,
    value: "session_id",
  },
  {
    title: "Player ID",
    align: "start",
    sortable: false,
    value: "player_id",
  },
  {
    title: "Brand Name",
    align: "start",
    sortable: false,
    value: "brand",
  },
  {
    title: "Player Country",
    align: "start",
    sortable: false,
    value: "player_country",
  },
  {
    title: "Total wagered (€)",
    align: "start",
    sortable: false,
    value: "total_bets",
  },
  {
    title: "Total payouts (€)",
    align: "start",
    sortable: false,
    value: "total_wins",
  },
  {
    title: "Refound (€)",
    align: "start",
    sortable: false,
    value: "total_refunds",
  },
  {
    title: "Refounds Count",
    align: "start",
    sortable: false,
    value: "total_refunds_count",
  },
  {
    title: "GGR (€)",
    align: "start",
    sortable: false,
    value: "ggr",
  },
  {
    title: "Bonus Bets (€)",
    align: "start",
    sortable: false,
    value: "bonus_bets",
  },
  {
    title: "Bonus Wins (€)",
    align: "start",
    sortable: false,
    value: "bonus_wins",
  },
  {
    title: "Bonus GGR (€)",
    align: "start",
    sortable: false,
    value: "bonus_ggr",
  },
  {
    title: "RTP",
    align: "start",
    sortable: false,
    value: "rtp",
  },
  {
    title: "Total Spins",
    align: "start",
    sortable: false,
    value: "total_spins",
  },
  {
    title: "Time open",
    align: "start",
    sortable: false,
    value: "time_open",
  },
  {
    title: "Time closed",
    align: "start",
    sortable: false,
    value: "time_closed",
  },
];
